services:
  news-dashboard:
    build: .
    container_name: news-dashboard
    ports:
      - "3000:3000"
      - "5555:5555"
    env_file:
      - docker.env
    volumes:
      # Persist database between container restarts
      - ./prisma:/app/prisma
      # Persist node_modules for faster rebuilds
      - /app/node_modules
      # Persist .next build cache
      - /app/.next
    networks:
      - news-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    # Temporarily disabled due to Docker Hub authentication issues
    # depends_on:
    #   - external-api-check

  # Service to check if external API is accessible - temporarily disabled
  # external-api-check:
  #   image: alpine:latest
  #   container_name: external-api-check
  #   command: >
  #     sh -c "
  #       apk add --no-cache curl &&
  #       echo '🔍 Checking external API accessibility...' &&
  #       until curl -f 'http://192.168.100.35:9051/api/posts/?page=1&page_size=1000&platform=F'; do
  #         echo '⏳ External API not ready, waiting...' &&
  #         sleep 10
  #       done &&
  #       echo '✅ External API is accessible!' &&
  #       exit 0
  #     "
  #   networks:
  #     - news-network
  #   restart: "no"

networks:
  news-network:
    driver: bridge

volumes:
  prisma-data:
    driver: local
